version: "3.7"

services:
  nomad:
    image: nomad_service_dev
    restart: always
    volumes:
      - ./:/app
    build: .
    ports:
      - 8000:8000
    networks:
      - default
networks:
  default:
      external: false
      name: auth_default
